import test from "node:test";
import assert from "node:assert/strict";
await import("../src/core.js"); await import("../src/api.js");
const core = globalThis.__NarrativeDirectorCore; const factory = globalThis.__NarrativeDirectorApi;
const story = { title: "Test", mainCharacterId: "hero", worldCard: { name: "Test", description: "Public", personality: "", scenario: "Opening" }, characters: [{ id: "hero", name: "Hero", aliases: [], isMain: true, public: { role: "Lead", description: "Visible", appearance: "", personality: "", scenario: "" }, curatorNotes: "Private" }], relationships: [], worldEntries: [], curatorGuide: "Guide", secrets: [{ id: "truth", title: "Truth", truth: "Hidden", knownByCharacterIds: ["hero"], revealCondition: "Explicit reveal", status: "locked" }], storylines: [{ id: "arc", title: "Arc", direction: "Develop", status: "active" }] };
const currentState = { summary: "Started", currentSituation: "Opening", revealedSecretIds: [], storylineStatuses: { arc: "active" }, characterStates: { hero: "Present" } };
function project() { return core.createProject({ id: "p", name: "Test", chatId: "chat-a", story, analysisConnectionId: "conn", initializationConnectionId: "conn" }); }
function harness(outputs = [{ rewrittenText: JSON.stringify(story) }]) { const calls = []; let index = 0; const books = new Map(); let next = 1; const metadata = { activeAgentIds: ["other"], activeLorebookIds: [], excludedLorebookIds: [] }; const api = factory.createApi({ apiFetch: async (path, options = {}) => { const method = options.method || "GET"; const body = options.body ? JSON.parse(options.body) : null; calls.push({ path, method, body }); if (path === "/agents/suite/rewrite") return outputs[Math.min(index++, outputs.length - 1)]; if (path === "/agents") return [{ type: core.CURATOR_TYPE }]; if (path === "/connections" || path === "/chats" || path.startsWith("/characters?")) return []; if (/^\/chats\/[^/]+$/.test(path)) return { id: "chat-a", metadata, characterIds: [] }; if (path.endsWith("/messages")) return []; if (path.endsWith("/metadata")) { Object.assign(metadata, body); return metadata; } if (path === "/characters") return { id: `character-${next++}` }; if (path === "/lorebooks") { if (method === "GET") return []; const row = { ...body, id: `book-${next++}` }; books.set(row.id, []); return row; } const match = path.match(/^\/lorebooks\/([^/]+)\/entries(?:\/([^/]+))?$/); if (match) { const rows = books.get(match[1]) || []; if (method === "GET") return rows; if (method === "POST") { const row = { ...body, id: `entry-${next++}` }; rows.push(row); books.set(match[1], rows); return row; } const found = rows.find((item) => item.id === match[2]); Object.assign(found, body); return found; } return {}; } }); return { api, calls, books, metadata }; }

test("analysis makes one request with the fixed v4 prompt", async () => { const shared = harness(); const result = await shared.api.analyzeStory("conn", "Fictional source", "Keep uncertain material private."); const rewrites = shared.calls.filter((row) => row.path === "/agents/suite/rewrite"); assert.equal(rewrites.length, 1); assert.equal(rewrites[0].body.instruction, core.ANALYSIS_PROMPT); assert.equal(result.title, story.title); });

test("invalid or truncated analysis never retries", async () => { const shared = harness([{ rewrittenText: '{"title":"cut"', finishReason: "length" }]); await assert.rejects(shared.api.analyzeStory("conn", "source", "rules"), /truncated/i); assert.equal(shared.calls.filter((row) => row.path === "/agents/suite/rewrite").length, 1); });

test("initialization makes one request and returns simplified state", async () => { const shared = harness([{ rewrittenText: JSON.stringify(currentState) }]); const result = await shared.api.initializeFromChat("conn", project(), [{ id: "m", role: "user", content: "Hello" }], { chatSummary: "Earlier" }); assert.deepEqual(result.state, currentState); assert.equal(shared.calls.filter((row) => row.path === "/agents/suite/rewrite").length, 1); });

test("guarded lorebook stores one Curator v4 entry", async () => { const shared = harness(); const result = await shared.api.syncProjectLorebook(project()); const rows = shared.books.get(result.lorebookId); assert.equal(rows.length, 1); assert.equal(rows[0].name, core.CURATOR_LOREBOOK_SENTINEL); assert.match(rows[0].content, /Private/); assert.deepEqual(Object.keys(result.entryIds), ["curator"]); });

test("existing v4 Curator entry is updated in place", async () => { const shared = harness(); shared.books.set("book-existing", [{ id: "entry-existing", name: core.CURATOR_LOREBOOK_SENTINEL }]); const existing = project(); existing.agentLorebookId = "book-existing"; existing.agentEntryIds = { curator: "entry-existing" }; await shared.api.syncProjectLorebook(existing); const writes = shared.calls.filter((row) => row.method === "PATCH" && row.path.includes("/entries/")); assert.equal(writes.length, 1); assert.equal(writes[0].body.name, core.CURATOR_LOREBOOK_SENTINEL); });

test("activation uses only the fixed Curator and preserves unrelated agents", async () => { const shared = harness(); await shared.api.updateChatActivation("chat-a", true); assert.deepEqual(shared.metadata.activeAgentIds, ["other", core.CURATOR_TYPE]); assert.ok(!shared.calls.some((row) => row.path === "/agents" && row.method !== "GET")); });
