import test from "node:test";
import assert from "node:assert/strict";
await import("../src/core.js"); await import("../src/api.js");
const core = globalThis.__NarrativeDirectorCore; const factory = globalThis.__NarrativeDirectorApi;
const story = { title: "Test", mainCharacterId: "hero", worldCard: { name: "Test", description: "Public", personality: "", scenario: "Opening" }, characters: [{ id: "hero", name: "Hero", aliases: [], isMain: true, public: { role: "Lead", description: "Visible", appearance: "", personality: "", scenario: "" }, directorNotes: "Private" }], worldEntries: [], directorGuide: "Guide", secrets: [{ id: "truth", title: "Truth", truth: "Hidden", knownByCharacterIds: ["hero"], revealCondition: "Explicit reveal", status: "locked" }], storylines: [{ id: "arc", title: "Arc", direction: "Develop", status: "active" }] };
const currentState = { summary: "Started", currentSituation: "Opening", revealedSecretIds: [], storylineStatuses: { arc: "active" }, characterStates: { hero: "Present" } };
function project() { return core.createProject({ id: "p", name: "Test", chatId: "chat-a", story, analysisConnectionId: "conn", initializationConnectionId: "conn" }); }
function harness(outputs = [{ rewrittenText: JSON.stringify(story) }]) { const calls = []; let index = 0; const books = new Map(); let next = 1; const metadata = { activeAgentIds: ["other"], activeLorebookIds: [], excludedLorebookIds: [] }; const api = factory.createApi({ apiFetch: async (path, options = {}) => { const method = options.method || "GET"; const body = options.body ? JSON.parse(options.body) : null; calls.push({ path, method, body }); if (path === "/agents/suite/rewrite") return outputs[Math.min(index++, outputs.length - 1)]; if (path === "/agents") return [{ type: core.DIRECTOR_TYPE }, { type: core.TRACKER_TYPE }]; if (path === "/connections" || path === "/chats" || path.startsWith("/characters?")) return []; if (/^\/chats\/[^/]+$/.test(path)) return { id: "chat-a", metadata, characterIds: [] }; if (path.endsWith("/messages")) return []; if (path.endsWith("/game-state")) return { playerStats: { customTrackerFields: [] } }; if (path.endsWith("/metadata")) { Object.assign(metadata, body); return metadata; } if (path === "/characters") return { id: `character-${next++}` }; if (path === "/lorebooks") { if (method === "GET") return []; const row = { ...body, id: `book-${next++}` }; books.set(row.id, []); return row; } const match = path.match(/^\/lorebooks\/([^/]+)\/entries(?:\/([^/]+))?$/); if (match) { const rows = books.get(match[1]) || []; if (method === "GET") return rows; if (method === "POST") { const row = { ...body, id: `entry-${next++}` }; rows.push(row); books.set(match[1], rows); return row; } const row = { ...rows.find((item) => item.id === match[2]), ...body }; return row; } return {}; } }); return { api, calls, books, metadata }; }

test("analysis makes exactly one request and sends editable rules as context", async () => { const shared = harness(); const rules = "Keep uncertain material private."; const result = await shared.api.analyzeStory("conn", "Fictional source", rules); const rewrites = shared.calls.filter((row) => row.path === "/agents/suite/rewrite"); assert.equal(rewrites.length, 1); assert.equal(rewrites[0].body.selectedText, "Fictional source"); assert.equal(rewrites[0].body.instruction, core.ANALYSIS_PROMPT); assert.deepEqual(rewrites[0].body.contextSections, [{ label: "User analysis rules", content: rules }]); assert.equal(result.title, story.title); });

test("invalid or truncated analysis never retries and preserves project plus raw response", async () => { const raw = '{"title":"cut"'; const shared = harness([{ rewrittenText: raw, finishReason: "length" }]); const before = project(); const snapshot = structuredClone(before); await assert.rejects(shared.api.analyzeStory("conn", "source", "rules"), /truncated/i); assert.deepEqual(before, snapshot); assert.equal(shared.calls.filter((row) => row.path === "/agents/suite/rewrite").length, 1); assert.equal(shared.api.getLastRawResponse(), raw); });

test("provider failure makes no automatic second request", async () => { const calls = []; const api = factory.createApi({ apiFetch: async (path) => { calls.push(path); throw new Error("provider unavailable"); } }); await assert.rejects(api.analyzeStory("conn", "source", "rules"), /provider unavailable/); assert.equal(calls.filter((path) => path === "/agents/suite/rewrite").length, 1); });

test("initialization makes one request and returns simplified state", async () => { const shared = harness([{ rewrittenText: JSON.stringify(currentState) }]); const result = await shared.api.initializeFromChat("conn", project(), [{ id: "m", role: "user", content: "Hello" }], { chatSummary: "Earlier" }); assert.deepEqual(result.state, currentState); assert.equal(shared.calls.filter((row) => row.path === "/agents/suite/rewrite").length, 1); assert.equal(shared.calls.find((row) => row.path === "/agents/suite/rewrite").body.instruction, core.INITIALIZATION_PROMPT); });

test("single guarded lorebook stores Director and Tracker v3 entries", async () => { const shared = harness(); const result = await shared.api.syncProjectLorebook(project()); const rows = shared.books.get(result.lorebookId); assert.equal(rows.length, 2); assert.deepEqual(rows.map((row) => row.name), [core.DIRECTOR_LOREBOOK_SENTINEL, core.TRACKER_LOREBOOK_SENTINEL]); const director = rows.find((row) => row.name === core.DIRECTOR_LOREBOOK_SENTINEL).content; const tracker = rows.find((row) => row.name === core.TRACKER_LOREBOOK_SENTINEL).content; assert.match(director, /Private/); assert.doesNotMatch(tracker, /Private|Hidden|Develop/); });

test("existing transport entry IDs are upgraded in place to v3", async () => { const shared = harness(); shared.books.set("old-book", [{ id: "old-director", name: "__ND_DIRECTOR_PROJECT_V2__" }, { id: "old-tracker", name: "__ND_TRACKER_PROJECT_V2__" }]); const migrated = project(); migrated.agentLorebookId = "old-book"; migrated.agentEntryIds = { director: "old-director", tracker: "old-tracker" }; await shared.api.syncProjectLorebook(migrated); const writes = shared.calls.filter((row) => row.method === "PATCH" && row.path.startsWith("/lorebooks/old-book/entries/")); assert.deepEqual(writes.map((row) => row.path), ["/lorebooks/old-book/entries/old-director", "/lorebooks/old-book/entries/old-tracker"]); assert.deepEqual(writes.map((row) => row.body.name), [core.DIRECTOR_LOREBOOK_SENTINEL, core.TRACKER_LOREBOOK_SENTINEL]); assert.ok(!shared.calls.some((row) => row.method === "POST" && row.path.startsWith("/lorebooks/old-book/entries"))); });

test("activation uses existing fixed agents and preserves unrelated agent types", async () => { const shared = harness(); await shared.api.updateChatActivation("chat-a", true); assert.deepEqual(shared.metadata.activeAgentIds, ["other", core.DIRECTOR_TYPE, core.TRACKER_TYPE]); assert.ok(!shared.calls.some((row) => row.path === "/agents" && row.method !== "GET")); });
