(() => {
  "use strict";
  if (globalThis.__narrativeDirectorLoaded) return; globalThis.__narrativeDirectorLoaded = true;
  const core = NarrativeDirectorCore; const storage = NarrativeDirectorStorage.createStore(); const api = NarrativeDirectorApi.createApi(marinara); const RULES_KEY = "analysisRulesV4";
  const state = { open: false, projects: [], currentId: "", draft: null, resources: { chats: [], connections: [] }, tab: "source", dirty: false, busy: false, rules: core.DEFAULT_ANALYSIS_RULES, initializationProposal: null, initializationInfo: null };
  const launcher = marinara.addElement(document.body, "button", { type: "button", class: "nd-launcher", textContent: "Narrative Curator", title: "Open Narrative Curator v4" });
  const root = marinara.addElement(document.body, "div", { class: "nd-root", "aria-hidden": "true" }); if (!launcher || !root) return;
  root.innerHTML = `
    <div class="nd-backdrop" data-action="close"></div><section class="nd-shell" role="dialog" aria-modal="true" aria-labelledby="nd-title" tabindex="-1">
      <header class="nd-header"><div><span class="nd-kicker">Private story workspace</span><h1 id="nd-title">Narrative Curator v4</h1></div><div class="nd-header-actions"><button class="nd-button nd-button-quiet" type="button" data-action="import">Import JSON</button><button class="nd-button nd-button-quiet" type="button" data-action="export">Export JSON</button><button class="nd-icon-button" type="button" data-action="close" aria-label="Close">×</button></div></header>
      <div class="nd-layout"><aside class="nd-sidebar"><div class="nd-sidebar-heading"><strong>Projects</strong><button class="nd-button nd-button-primary nd-button-small" type="button" data-action="new">New</button></div><div class="nd-project-list" data-slot="projects"></div></aside>
        <main class="nd-main"><div class="nd-empty" data-slot="empty"><h2>Shape a story without exposing its secrets</h2><p>Analyze one compact plan, edit public resources directly, then synchronize the private guide.</p><button class="nd-button nd-button-primary" type="button" data-action="new">Create project</button></div>
          <form class="nd-editor" data-slot="editor" hidden><div class="nd-editor-head"><label class="nd-field"><span>Project name</span><input name="name" maxlength="300"></label><span class="nd-save-state" data-slot="save-state">Local draft</span></div>
            <nav class="nd-tabs" aria-label="Project sections">${["source", "public", "private", "initialize", "agents"].map((tab) => `<button type="button" data-tab="${tab}" aria-selected="${tab === "source"}">${tab[0].toUpperCase()}${tab.slice(1)}</button>`).join("")}</nav>
            <section class="nd-panel" data-panel="source"><div class="nd-form-grid"><label class="nd-field"><span>Project type</span><select name="projectType"><option value="character_focus">Character focus</option><option value="world_ensemble">World / ensemble</option></select></label><label class="nd-field"><span>Chat</span><select name="chatId"><option value="">Choose chat</option></select></label></div>
              <label class="nd-field"><span>Story source</span><textarea name="sourceText" rows="14" maxlength="50000" placeholder="Paste a story or planning document, up to 50,000 characters"></textarea><small><span data-slot="source-count">0</span> / 50,000</small></label>
              <details class="nd-guide"><summary>Regras de análise</summary><div class="nd-intro"><span>Estas regras controlam como a IA interpreta e organiza a história. A estrutura JSON permanece protegida pela extensão.</span></div><label class="nd-field"><span>Regras</span><textarea name="analysisRules" rows="12" maxlength="${core.MAX_ANALYSIS_RULES_LENGTH}"></textarea><small><span data-slot="rules-count">0</span> / ${core.MAX_ANALYSIS_RULES_LENGTH}</small></label><div class="nd-inline-actions"><button class="nd-button nd-button-primary nd-button-small" type="button" data-action="save-rules">Salvar</button><button class="nd-button nd-button-quiet nd-button-small" type="button" data-action="reset-rules">Restaurar padrão</button><span class="nd-save-state" data-slot="rules-state">Salvo localmente</span></div></details>
              <div class="nd-action-strip"><label class="nd-field"><span>Analysis connection</span><select name="analysisConnectionId"><option value="">Choose connection</option></select></label><button class="nd-button nd-button-primary" type="button" data-action="analyze">Analyze story</button></div><div class="nd-progress" data-slot="analysis-progress" aria-live="polite" hidden><strong>Analyzing story…</strong></div>
              <details class="nd-raw" data-slot="raw-section" hidden><summary>Raw AI response</summary><p class="nd-warning">May contain the complete story and private data. Session memory only, never saved or exported.</p><pre data-slot="raw-response"></pre><button class="nd-button nd-button-quiet nd-button-small" type="button" data-action="copy-raw">Copy response</button></details>
            </section>
            <section class="nd-panel" data-panel="public" hidden><div class="nd-warning">Only information safe for immediate narrator context belongs here.</div><div class="nd-form-grid"><label class="nd-field"><span>Story title</span><input name="storyTitle"></label><label class="nd-field"><span>Primary character</span><select name="primaryCharacterEntityId"></select></label></div>
              <section class="nd-edit-section"><div class="nd-section-head"><h3>World card</h3></div><div class="nd-form-grid"><label class="nd-field"><span>Name</span><input name="worldName"></label><label class="nd-field"><span>Personality</span><textarea name="worldPersonality" rows="3"></textarea></label></div><label class="nd-field"><span>Description</span><textarea name="worldDescription" rows="5"></textarea></label><label class="nd-field"><span>Scenario</span><textarea name="worldScenario" rows="5"></textarea></label></section>
              <section class="nd-edit-section"><div class="nd-section-head"><h3>Public character profiles</h3><button class="nd-button nd-button-quiet nd-button-small" type="button" data-action="add-character">Add character</button></div><div data-slot="public-characters"></div></section>
              <section class="nd-edit-section"><div class="nd-section-head"><h3>World entries</h3><button class="nd-button nd-button-quiet nd-button-small" type="button" data-action="add-world-entry">Add entry</button></div><div data-slot="world-entries"></div></section>
              <div class="nd-inline-actions"><button class="nd-button nd-button-quiet" type="button" data-action="refresh-preview">Refresh preview</button></div><div class="nd-preview-grid"><section><h3>Character cards</h3><div data-slot="card-preview"></div></section><section><h3>Lorebook</h3><div data-slot="lorebook-preview"></div></section></div>
              <label class="nd-check"><input type="checkbox" name="applyConfirmed"><span>I reviewed the public output and want to create only missing resources.</span></label><button class="nd-button nd-button-primary" type="button" data-action="apply">Create public resources</button>
            </section>
            <section class="nd-panel" data-panel="private" hidden><div class="nd-intro"><strong>Curator-only guide</strong><span>These fields never participate in public card or lorebook compilation.</span></div><label class="nd-field"><span>Curator guide</span><textarea name="curatorGuide" rows="12"></textarea></label><label class="nd-field"><span>Story-specific editorial instructions</span><textarea name="editorialInstructions" rows="5"></textarea></label>
              <section class="nd-edit-section"><div class="nd-section-head"><h3>Character notes</h3></div><div data-slot="private-characters"></div></section>
              <section class="nd-edit-section"><div class="nd-section-head"><h3>Relationships</h3><button class="nd-button nd-button-quiet nd-button-small" type="button" data-action="add-relationship">Add relationship</button></div><div data-slot="relationships"></div></section>
              <section class="nd-edit-section"><div class="nd-section-head"><h3>Important secrets</h3><button class="nd-button nd-button-quiet nd-button-small" type="button" data-action="add-secret">Add secret</button></div><div data-slot="secrets"></div></section>
              <section class="nd-edit-section"><div class="nd-section-head"><h3>Broad storylines</h3><button class="nd-button nd-button-quiet nd-button-small" type="button" data-action="add-storyline">Add storyline</button></div><div data-slot="storylines"></div></section>
            </section>
            <section class="nd-panel" data-panel="initialize" hidden><div class="nd-intro"><strong>Initialize from existing chat</strong><span>One request uses the chat summary and the most recent active messages that fit. Past messages are never modified.</span></div><div class="nd-action-strip"><label class="nd-field"><span>Initialization connection</span><select name="initializationConnectionId"><option value="">Choose connection</option></select></label><button class="nd-button nd-button-primary" type="button" data-action="initialize">Initialize</button></div><div class="nd-progress" data-slot="initialization-progress" hidden><strong>Analyzing current chat…</strong></div><div class="nd-warning" data-slot="omitted-messages" hidden></div><div data-slot="initialization-review"><p>No proposal loaded.</p></div><div class="nd-inline-actions" data-slot="initialization-actions" hidden><button class="nd-button nd-button-primary" type="button" data-action="confirm-initialization">Confirm and synchronize</button><button class="nd-button nd-button-quiet" type="button" data-action="discard-initialization">Discard</button></div></section>
            <section class="nd-panel" data-panel="agents" hidden><div class="nd-intro"><strong>One fixed Curator</strong><span>Import the v4 preset once, choose its connection in Marinara, then activate it for this chat.</span></div><div class="nd-agent-statuses"><section><code>${core.CURATOR_TYPE}</code><strong data-slot="curator-status">Checking…</strong></section></div><div class="nd-warning">The private transport lorebook remains outside normal active lorebooks. Do not select it as a Knowledge Router source. Deactivate the old v3 Director and Tracker before activating v4.</div><div class="nd-inline-actions"><button class="nd-button nd-button-primary" type="button" data-action="sync-lorebook">Synchronize Curator lorebook</button><button class="nd-button nd-button-quiet" type="button" data-action="refresh-agents">Refresh status</button></div><div class="nd-inline-actions"><button class="nd-button nd-button-primary" type="button" data-action="activate">Activate Curator</button><button class="nd-button nd-button-danger" type="button" data-action="deactivate">Deactivate Curator</button></div></section>
            <div class="nd-errors" data-slot="errors" role="alert" hidden></div><footer class="nd-footer"><button class="nd-button nd-button-danger-quiet" type="button" data-action="delete">Delete local draft</button><button class="nd-button nd-button-primary" type="submit">Save local draft</button></footer>
          </form></main></div><div class="nd-toasts" data-slot="toasts" aria-live="polite"></div><input data-slot="import-file" type="file" accept="application/json,.json" hidden>
    </section>`;

  const $ = (selector, within = root) => within.querySelector(selector); const $$ = (selector, within = root) => Array.from(within.querySelectorAll(selector)); const editor = $('[data-slot="editor"]'); const fields = Object.fromEntries($$("[name]", editor).map((field) => [field.name, field]));
  function toast(message, tone = "info") { const row = document.createElement("div"); row.className = `nd-toast is-${tone}`; row.textContent = message; $('[data-slot="toasts"]').appendChild(row); setTimeout(() => row.remove(), 4500); }
  function errors(rows = []) { const box = $('[data-slot="errors"]'); box.hidden = !rows.length; box.replaceChildren(); for (const message of rows) { const p = document.createElement("p"); p.textContent = message; box.appendChild(p); } }
  function option(value, label) { const row = document.createElement("option"); row.value = value; row.textContent = label; return row; }
  function fillSelect(select, rows, selected, placeholder) { select.replaceChildren(option("", placeholder)); for (const row of rows) select.appendChild(option(row.id, row.label)); select.value = selected || ""; }
  function nextId(prefix, rows) { let index = rows.length + 1; while (rows.some((row) => row.id === `${prefix}_${index}`)) index++; return `${prefix}_${index}`; }
  function setPath(target, path, value) { const keys = path.split("."); const leaf = keys.pop(); let row = target; for (const key of keys) row = row[key]; row[leaf] = value; }
  function syncStoryFromEditor(story) { story.title = fields.storyTitle.value; story.worldCard = { name: fields.worldName.value, description: fields.worldDescription.value, personality: fields.worldPersonality.value, scenario: fields.worldScenario.value }; story.curatorGuide = fields.curatorGuide.value; for (const input of $$('[data-collection][data-index][data-path]')) { const row = story[input.dataset.collection]?.[Number(input.dataset.index)]; if (!row) continue; const value = input.dataset.valueType === "list" ? input.value.split(/[\n,]/).map((item) => item.trim()).filter(Boolean) : input.dataset.valueType === "boolean" ? input.checked : input.value; setPath(row, input.dataset.path, value); } story.mainCharacterId = fields.primaryCharacterEntityId.value; return story; }
  function readDraft() { if (!state.draft) return null; const story = syncStoryFromEditor(structuredClone(state.draft.story)); return core.createProject({ ...state.draft, name: fields.name.value, projectType: fields.projectType.value, chatId: fields.chatId.value, analysisConnectionId: fields.analysisConnectionId.value, initializationConnectionId: fields.initializationConnectionId.value, sourceText: fields.sourceText.value, story, primaryCharacterEntityId: fields.primaryCharacterEntityId.value, separateCharacterEntityIds: $$('[data-separate-character]').filter((input) => input.checked).map((input) => input.value), editorialInstructions: fields.editorialInstructions.value, updatedAt: new Date().toISOString() }, state.draft.createdAt); }
  function bindInput(row, collection, index, definition) { const label = document.createElement("label"); label.className = "nd-field"; const span = document.createElement("span"); span.textContent = definition.label; const input = definition.type === "select" ? document.createElement("select") : definition.type === "boolean" ? document.createElement("input") : definition.type === "text" ? document.createElement("input") : document.createElement("textarea"); input.dataset.collection = collection; input.dataset.index = String(index); input.dataset.path = definition.path; const keys = definition.path.split("."); const value = keys.reduce((target, key) => target?.[key], row); if (definition.type === "select") { for (const item of definition.options) input.append(option(item, item)); input.value = value || definition.options[0]; } else if (definition.type === "boolean") { input.type = "checkbox"; input.checked = value === true; input.dataset.valueType = "boolean"; } else { input.value = Array.isArray(value) ? value.join("\n") : value || ""; if (definition.type === "list") input.dataset.valueType = "list"; if (input.tagName === "TEXTAREA") input.rows = definition.rows || 3; } label.append(span, input); return label; }
  function collectionEditor(slot, collection, rows, title, definitions, removable = true) { const container = $(`[data-slot="${slot}"]`); container.replaceChildren(); if (!rows.length) { const p = document.createElement("p"); p.textContent = "None yet."; container.appendChild(p); return; } rows.forEach((row, index) => { const details = document.createElement("details"); details.open = rows.length <= 2; const summary = document.createElement("summary"); summary.textContent = title(row); details.append(summary); for (const definition of definitions) details.append(bindInput(row, collection, index, definition)); if (removable) { const remove = document.createElement("button"); remove.type = "button"; remove.className = "nd-button nd-button-danger-quiet nd-button-small"; remove.dataset.action = "remove-item"; remove.dataset.collection = collection; remove.dataset.index = String(index); remove.textContent = "Remove"; details.append(remove); } container.append(details); }); }
  function renderPublicEditors(project) { const story = project.story; fields.storyTitle.value = story.title; fields.worldName.value = story.worldCard.name; fields.worldDescription.value = story.worldCard.description; fields.worldPersonality.value = story.worldCard.personality; fields.worldScenario.value = story.worldCard.scenario; fillSelect(fields.primaryCharacterEntityId, story.characters.map((row) => ({ id: row.id, label: row.name })), project.primaryCharacterEntityId || story.mainCharacterId, "Choose primary character");
    collectionEditor("public-characters", "characters", story.characters, (row) => row.name, [{ path: "id", label: "ID", type: "text" }, { path: "name", label: "Name", type: "text" }, { path: "aliases", label: "Aliases, one per line", type: "list" }, { path: "isMain", label: "Main character", type: "boolean" }, { path: "public.role", label: "Public role", type: "text" }, { path: "public.description", label: "Public description", rows: 4 }, { path: "public.appearance", label: "Public appearance" }, { path: "public.personality", label: "Public personality" }, { path: "public.scenario", label: "Public scenario" }]);
    for (const [index, details] of $$('[data-slot="public-characters"] details').entries()) { const check = document.createElement("label"); check.className = "nd-check"; const input = document.createElement("input"); input.type = "checkbox"; input.value = story.characters[index].id; input.dataset.separateCharacter = ""; input.checked = project.separateCharacterEntityIds.includes(story.characters[index].id); const span = document.createElement("span"); span.textContent = "Create a separate character card"; check.append(input, span); details.append(check); }
    collectionEditor("world-entries", "worldEntries", story.worldEntries, (row) => row.name, [{ path: "id", label: "ID", type: "text" }, { path: "name", label: "Name", type: "text" }, { path: "keys", label: "Activation keys, one per line", type: "list" }, { path: "content", label: "Public content", rows: 5 }]); }
  function renderPrivateEditors(project) { fields.curatorGuide.value = project.story.curatorGuide; fields.editorialInstructions.value = project.editorialInstructions; collectionEditor("private-characters", "characters", project.story.characters, (row) => row.name, [{ path: "curatorNotes", label: "Curator notes", rows: 5 }], false); collectionEditor("relationships", "relationships", project.story.relationships, (row) => row.id, [{ path: "id", label: "ID", type: "text" }, { path: "characterIds", label: "Character IDs, one per line", type: "list" }, { path: "publicSummary", label: "Public summary", rows: 3 }, { path: "privateSummary", label: "Private summary", rows: 4 }]); collectionEditor("secrets", "secrets", project.story.secrets, (row) => row.title, [{ path: "id", label: "ID", type: "text" }, { path: "title", label: "Title", type: "text" }, { path: "truth", label: "Truth", rows: 4 }, { path: "knownByCharacterIds", label: "Known by character IDs", type: "list" }, { path: "revealCondition", label: "Reveal condition", rows: 3 }, { path: "status", label: "Status", type: "select", options: core.SECRET_STATUSES }]); collectionEditor("storylines", "storylines", project.story.storylines, (row) => row.title, [{ path: "id", label: "ID", type: "text" }, { path: "title", label: "Title", type: "text" }, { path: "direction", label: "Adaptable direction", rows: 5 }, { path: "status", label: "Status", type: "select", options: core.STORYLINE_STATUSES }]); }
  function renderPreview(project) { const cards = $('[data-slot="card-preview"]'); const lore = $('[data-slot="lorebook-preview"]'); cards.replaceChildren(); lore.replaceChildren(); try { const output = core.compilePublicResources(project); for (const card of output.cards) { const details = document.createElement("details"); const summary = document.createElement("summary"); summary.textContent = card.data.name; const pre = document.createElement("pre"); pre.textContent = JSON.stringify({ description: card.data.description, personality: card.data.personality, scenario: card.data.scenario, appearance: card.data.extensions.appearance }, null, 2); details.append(summary, pre); cards.append(details); } for (const entry of output.lorebookEntries) { const details = document.createElement("details"); const summary = document.createElement("summary"); summary.textContent = entry.name; const pre = document.createElement("pre"); pre.textContent = entry.content; details.append(summary, pre); lore.append(details); } if (!output.cards.length) cards.append("No card content yet."); if (!output.lorebookEntries.length) lore.append("No lorebook entries yet."); } catch (error) { lore.append(error.message); } }
  function renderRaw() { const raw = api.getLastRawResponse(); $('[data-slot="raw-section"]').hidden = !raw; $('[data-slot="raw-response"]').textContent = raw; }
  function renderProjectList() { const container = $('[data-slot="projects"]'); container.replaceChildren(); for (const project of state.projects) { const button = document.createElement("button"); button.type = "button"; button.dataset.projectId = project.id; button.className = project.id === state.currentId ? "is-active" : ""; const strong = document.createElement("strong"); strong.textContent = project.name; const span = document.createElement("span"); span.textContent = project.needsReview ? "Migrated, review needed" : project.chatId ? "Chat linked" : "Local draft"; button.append(strong, span); container.append(button); } }
  function writeDraft(value) { const project = core.createProject(value, value.createdAt); state.draft = project; fields.name.value = project.name; fields.projectType.value = project.projectType; fields.sourceText.value = project.sourceText; fields.analysisRules.value = state.rules; fields.editorialInstructions.value = project.editorialInstructions; fillSelect(fields.chatId, state.resources.chats, project.chatId, "Choose chat"); fillSelect(fields.analysisConnectionId, state.resources.connections, project.analysisConnectionId, "Choose connection"); fillSelect(fields.initializationConnectionId, state.resources.connections, project.initializationConnectionId || project.analysisConnectionId, "Choose connection"); $('[data-slot="source-count"]').textContent = String(project.sourceText.length); $('[data-slot="rules-count"]').textContent = String(state.rules.length); renderPublicEditors(project); renderPrivateEditors(project); renderPreview(project); renderInitialization(null); renderRaw(); renderProjectList(); }
  function renderEditor() { $('[data-slot="empty"]').hidden = Boolean(state.draft); editor.hidden = !state.draft; if (state.draft) writeDraft(state.draft); }
  async function refreshResources() { const [chats, connections] = await Promise.all([api.listChats(), api.listConnections()]); state.resources.chats = chats.map((row) => ({ id: row.id, label: row.name || row.title || row.id })); state.resources.connections = connections.map((row) => ({ id: row.id, label: `${row.name || "Connection"} · ${row.model || row.provider}` })); }
  async function refreshAll() { try { await Promise.all([refreshResources(), storage.open()]); state.rules = core.analysisRules(await storage.getMeta(RULES_KEY)); state.projects = (await storage.listProjects()).map((row) => core.createProject(row, row.createdAt)); if (state.currentId) state.draft = state.projects.find((row) => row.id === state.currentId) || state.draft; renderEditor(); } catch (error) { errors([error.message]); } }
  function newProject() { const project = core.createProject(); state.currentId = project.id; state.draft = project; state.dirty = true; setTab("source"); renderEditor(); }
  async function selectProject(id) { if (state.dirty && !window.confirm("Discard unsaved local edits?")) return; const row = await storage.getProject(id); if (!row) return; state.currentId = id; state.draft = core.createProject(row, row.createdAt); state.dirty = false; renderEditor(); }
  async function saveProject() { const project = readDraft(); if (!project) return; const validation = core.validateProject(project); if (!validation.valid) return errors(validation.errors); await storage.saveProject(project); state.projects = (await storage.listProjects()).map((row) => core.createProject(row, row.createdAt)); state.draft = project; state.dirty = false; $('[data-slot="save-state"]').textContent = "Saved locally"; renderProjectList(); toast("Local draft saved.", "success"); }
  async function deleteProject() { if (!state.draft || !window.confirm("Delete this local draft? Server resources are not deleted.")) return; await storage.deleteProject(state.draft.id); state.projects = (await storage.listProjects()).map((row) => core.createProject(row, row.createdAt)); state.currentId = ""; state.draft = null; state.dirty = false; renderEditor(); }
  async function saveRules() { const value = fields.analysisRules.value.trim(); if (!value) return errors(["Rules cannot be empty. Restore the default instead."]); try { await storage.setMeta(RULES_KEY, value); state.rules = core.analysisRules(value); fields.analysisRules.value = state.rules; $('[data-slot="rules-state"]').textContent = "Salvo localmente"; toast("Regras salvas.", "success"); } catch (error) { errors([error.message]); } }
  async function resetRules() { try { await storage.setMeta(RULES_KEY, core.DEFAULT_ANALYSIS_RULES); state.rules = core.DEFAULT_ANALYSIS_RULES; fields.analysisRules.value = state.rules; $('[data-slot="rules-count"]').textContent = String(state.rules.length); $('[data-slot="rules-state"]').textContent = "Padrão restaurado"; toast("Regras restauradas.", "success"); } catch (error) { errors([error.message]); } }
  function setBusy(value) { state.busy = value; $$('button, input, select, textarea', editor).forEach((node) => { node.disabled = value; }); }
  async function analyze() { const project = readDraft(); if (!project) return; $('[data-slot="analysis-progress"]').hidden = false; setBusy(true); errors([]); try { const story = await api.analyzeStory(project.analysisConnectionId, project.sourceText, state.rules); state.draft = core.applyStory(project, story); state.dirty = true; writeDraft(state.draft); setTab("public"); toast("Compact story ready for review.", "success"); } catch (error) { renderRaw(); errors([error.message]); } finally { setBusy(false); $('[data-slot="analysis-progress"]').hidden = true; } }
  function addItem(collection) { const project = readDraft(); if (!project) return; const story = structuredClone(project.story); if (collection === "characters") story.characters.push({ id: nextId("character", story.characters), name: "New character", aliases: [], isMain: false, public: { role: "", description: "", appearance: "", personality: "", scenario: "" }, curatorNotes: "" }); if (collection === "relationships") story.relationships.push({ id: nextId("relationship", story.relationships), characterIds: [], publicSummary: "", privateSummary: "" }); if (collection === "worldEntries") story.worldEntries.push({ id: nextId("entry", story.worldEntries), name: "New entry", keys: [], content: "" }); if (collection === "secrets") story.secrets.push({ id: nextId("secret", story.secrets), title: "New secret", truth: "", knownByCharacterIds: [], revealCondition: "", status: "locked" }); if (collection === "storylines") story.storylines.push({ id: nextId("storyline", story.storylines), title: "New storyline", direction: "", status: "inactive" }); state.draft = core.createProject({ ...project, story }, project.createdAt); state.dirty = true; renderPublicEditors(state.draft); renderPrivateEditors(state.draft); }
  function removeItem(collection, index) { const project = readDraft(); if (!project) return; const story = structuredClone(project.story); story[collection].splice(index, 1); state.draft = core.createProject({ ...project, story }, project.createdAt); state.dirty = true; renderPublicEditors(state.draft); renderPrivateEditors(state.draft); renderPreview(state.draft); }
  async function applyResources() { let project = readDraft(); if (!project) return; if (!fields.applyConfirmed.checked) return errors(["Confirm the public preview before creating resources."]); if (!project.chatId) return errors(["Choose a chat first."]); let preview; try { preview = core.compilePublicResources(project); } catch (error) { return errors([error.message]); } setBusy(true); const failures = []; try { const characterIds = { ...project.publicResourceIds.characterIds }; for (const card of preview.cards) if (!characterIds[card.entityId]) try { const created = await api.createCharacter({ data: card.data }); if (!core.cleanId(created?.id)) throw new Error("No character ID returned."); characterIds[card.entityId] = created.id; } catch (error) { failures.push(`${card.data.name}: ${error.message}`); } let lorebookId = project.publicResourceIds.lorebookId; const entryIds = { ...project.publicResourceIds.entryIds }; if (preview.lorebookEntries.length && !lorebookId) try { const created = await api.createLorebook(preview.lorebook); lorebookId = core.cleanId(created?.id); if (!lorebookId) throw new Error("No lorebook ID returned."); } catch (error) { failures.push(`Lorebook: ${error.message}`); } if (lorebookId) for (const entry of preview.lorebookEntries) if (!entryIds[entry.entityId]) try { const created = await api.createLorebookEntry(lorebookId, { name: entry.name, description: entry.description, content: entry.content, keys: entry.keys }); if (!core.cleanId(created?.id)) throw new Error("No entry ID returned."); entryIds[entry.entityId] = created.id; } catch (error) { failures.push(`${entry.name}: ${error.message}`); } const createdIds = Object.values(characterIds); if (createdIds.length) await api.associateCharactersWithChat(project.chatId, createdIds); if (lorebookId) await api.associateLorebookWithChat(project.chatId, lorebookId); project = core.createProject({ ...project, associatedChatId: project.chatId, publicResourceIds: { characterIds, lorebookId, entryIds } }, project.createdAt); await storage.saveProject(project); state.draft = project; state.projects = (await storage.listProjects()).map((row) => core.createProject(row, row.createdAt)); fields.applyConfirmed.checked = false; failures.length ? errors(failures) : toast("Public resources created and linked.", "success"); } catch (error) { errors([error.message, ...failures]); } finally { setBusy(false); } }
  function renderInitialization(proposal) { const container = $('[data-slot="initialization-review"]'); container.replaceChildren(); $('[data-slot="initialization-actions"]').hidden = !proposal; if (!proposal) { container.append("No proposal loaded."); return; } const summary = document.createElement("label"); summary.className = "nd-field"; summary.innerHTML = "<span>Accumulated summary</span>"; const summaryInput = document.createElement("textarea"); summaryInput.rows = 5; summaryInput.dataset.initField = "summary"; summaryInput.value = proposal.summary; summary.append(summaryInput); const situation = document.createElement("label"); situation.className = "nd-field"; situation.innerHTML = "<span>Current situation</span>"; const situationInput = document.createElement("textarea"); situationInput.rows = 4; situationInput.dataset.initField = "currentSituation"; situationInput.value = proposal.currentSituation; situation.append(situationInput); container.append(summary, situation); const secretBox = document.createElement("section"); secretBox.className = "nd-edit-section"; secretBox.innerHTML = "<h3>Revealed secrets</h3>"; for (const secret of state.draft.story.secrets) { const label = document.createElement("label"); label.className = "nd-check"; const input = document.createElement("input"); input.type = "checkbox"; input.dataset.initSecret = secret.id; input.checked = proposal.revealedSecretIds.includes(secret.id); const span = document.createElement("span"); span.textContent = secret.title; label.append(input, span); secretBox.append(label); } container.append(secretBox); const storylineBox = document.createElement("section"); storylineBox.className = "nd-edit-section"; storylineBox.innerHTML = "<h3>Storylines</h3>"; for (const storyline of state.draft.story.storylines) { const label = document.createElement("label"); label.className = "nd-field"; const span = document.createElement("span"); span.textContent = storyline.title; const select = document.createElement("select"); select.dataset.initStoryline = storyline.id; for (const status of core.STORYLINE_STATUSES) select.append(option(status, status)); select.value = proposal.storylineStatuses[storyline.id] || storyline.status; label.append(span, select); storylineBox.append(label); } container.append(storylineBox); const characterBox = document.createElement("section"); characterBox.className = "nd-edit-section"; characterBox.innerHTML = "<h3>Character states</h3>"; for (const character of state.draft.story.characters) { const label = document.createElement("label"); label.className = "nd-field"; const span = document.createElement("span"); span.textContent = character.name; const input = document.createElement("input"); input.dataset.initCharacter = character.id; input.value = proposal.characterStates[character.id] || ""; label.append(span, input); characterBox.append(label); } container.append(characterBox); }
  function readInitialization() { return core.normalizeState({ summary: $('[data-init-field="summary"]')?.value || "", currentSituation: $('[data-init-field="currentSituation"]')?.value || "", revealedSecretIds: $$('[data-init-secret]').filter((row) => row.checked).map((row) => row.dataset.initSecret), storylineStatuses: Object.fromEntries($$('[data-init-storyline]').map((row) => [row.dataset.initStoryline, row.value])), characterStates: Object.fromEntries($$('[data-init-character]').flatMap((row) => row.value.trim() ? [[row.dataset.initCharacter, row.value.trim()]] : [])) }, state.draft.story, true); }
  async function initialize() { const project = readDraft(); if (!project?.chatId) return errors(["Choose a chat."]); $('[data-slot="initialization-progress"]').hidden = false; setBusy(true); try { const [messages, chat] = await Promise.all([api.listChatMessages(project.chatId), api.getChat(project.chatId)]); const result = await api.initializeFromChat(project.initializationConnectionId, project, messages, { chatSummary: chat?.summary || core.parseMetadata(chat?.metadata).summary }); state.initializationProposal = result.state; state.initializationInfo = result; renderInitialization(result.state); const omitted = $('[data-slot="omitted-messages"]'); omitted.hidden = !result.omittedMessageCount; omitted.textContent = result.omittedMessageCount ? `${result.omittedMessageCount} older message${result.omittedMessageCount === 1 ? " was" : "s were"} omitted to fit the request limit.` : ""; toast("Initialization proposal ready.", "success"); } catch (error) { errors([error.message]); } finally { setBusy(false); $('[data-slot="initialization-progress"]').hidden = true; } }
  async function confirmInitialization() { if (!state.initializationProposal) return; let project = readDraft(); try { const confirmedState = readInitialization(); project = core.createProject({ ...project, confirmedState }, project.createdAt); setBusy(true); const synced = await api.syncProjectLorebook(project); project = core.createProject({ ...project, agentLorebookId: synced.lorebookId, agentEntryIds: synced.entryIds, lorebookSyncedChatId: project.chatId, lorebookSyncedAt: new Date().toISOString() }, project.createdAt); await storage.saveProject(project); state.draft = project; state.projects = (await storage.listProjects()).map((row) => core.createProject(row, row.createdAt)); state.initializationProposal = null; renderInitialization(null); toast("State confirmed and Curator lorebook synchronized.", "success"); } catch (error) { errors([error.message]); } finally { setBusy(false); } }
  async function refreshAgents() { if (!state.draft?.chatId) return; try { const statuses = await api.getAgentStatuses(state.draft.chatId); $('[data-slot="curator-status"]').textContent = statuses.curator.status; } catch (error) { errors([error.message]); } }
  async function syncLorebook() { const project = readDraft(); if (!project?.chatId) return errors(["Choose a chat."]); setBusy(true); try { const synced = await api.syncProjectLorebook(project); const saved = core.createProject({ ...project, agentLorebookId: synced.lorebookId, agentEntryIds: synced.entryIds, lorebookSyncedChatId: project.chatId, lorebookSyncedAt: new Date().toISOString() }, project.createdAt); await storage.saveProject(saved); state.draft = saved; state.projects = (await storage.listProjects()).map((row) => core.createProject(row, row.createdAt)); toast("Curator lorebook synchronized.", "success"); } catch (error) { errors([error.message]); } finally { setBusy(false); } }
  async function activate(active) { const project = readDraft(); if (!project?.chatId) return errors(["Choose a chat."]); try { await api.updateChatActivation(project.chatId, active); await refreshAgents(); toast(active ? "Agents activated." : "Agents deactivated.", "success"); } catch (error) { errors([error.message]); } }
  function exportJson() { const blob = new Blob([JSON.stringify(core.exportBundle(state.projects), null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "narrative-curator-v4.json"; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
  async function importJson(file) { if (!file) return; try { const value = JSON.parse(await file.text()); if (value?.kind === core.BUNDLE_KIND) { const projects = core.importBundle(value); const current = new Map(state.projects.map((row) => [row.id, row])); for (const project of projects) current.set(project.id, project); await storage.replaceProjects([...current.values()]); state.projects = (await storage.listProjects()).map((row) => core.createProject(row, row.createdAt)); state.currentId = projects[0]?.id || ""; state.draft = projects[0] || null; state.dirty = false; renderEditor(); toast(`Imported ${projects.length} project${projects.length === 1 ? "" : "s"}.`, "success"); } else { if (!state.draft) throw new Error("Open a project before importing an isolated v4 story object."); const story = core.normalizeStory(value, true); state.draft = core.applyStory(readDraft(), story); state.dirty = true; writeDraft(state.draft); setTab("public"); toast("Story v4 applied to the open project. Review and save the draft.", "success"); } } catch (error) { errors([error.message]); } }
  function setTab(tab) { state.tab = tab; $$('[data-tab]').forEach((button) => button.setAttribute("aria-selected", String(button.dataset.tab === tab))); $$('[data-panel]').forEach((panel) => { panel.hidden = panel.dataset.panel !== tab; }); if (tab === "public" && state.draft) renderPreview(readDraft()); if (tab === "agents") void refreshAgents(); }
  function openPanel() { state.open = true; root.classList.add("is-open"); root.setAttribute("aria-hidden", "false"); document.body.classList.add("nd-body-locked"); void refreshAll(); }
  function closePanel() { state.open = false; root.classList.remove("is-open"); root.setAttribute("aria-hidden", "true"); document.body.classList.remove("nd-body-locked"); api.clearLastRawResponse(); }

  marinara.on(launcher, "click", openPanel); marinara.on(root, "click", (event) => { const tab = event.target.closest?.("[data-tab]"); if (tab) return setTab(tab.dataset.tab); const project = event.target.closest?.("[data-project-id]"); if (project) return void selectProject(project.dataset.projectId); const target = event.target.closest?.("[data-action]"); const action = target?.dataset.action; if (!action) return;
    if (action === "close") closePanel(); if (action === "new") newProject(); if (action === "delete") void deleteProject(); if (action === "analyze") void analyze(); if (action === "save-rules") void saveRules(); if (action === "reset-rules") void resetRules(); if (action === "copy-raw") navigator.clipboard.writeText(api.getLastRawResponse()).then(() => toast("Raw response copied.", "success"), () => toast("Clipboard unavailable.", "error"));
    if (action === "add-character") addItem("characters"); if (action === "add-relationship") addItem("relationships"); if (action === "add-world-entry") addItem("worldEntries"); if (action === "add-secret") addItem("secrets"); if (action === "add-storyline") addItem("storylines"); if (action === "remove-item") removeItem(target.dataset.collection, Number(target.dataset.index)); if (action === "refresh-preview") renderPreview(readDraft()); if (action === "apply") void applyResources();
    if (action === "initialize") void initialize(); if (action === "confirm-initialization") void confirmInitialization(); if (action === "discard-initialization") { state.initializationProposal = null; renderInitialization(null); } if (action === "sync-lorebook") void syncLorebook(); if (action === "refresh-agents") void refreshAgents(); if (action === "activate") void activate(true); if (action === "deactivate") void activate(false); if (action === "export") exportJson(); if (action === "import") $('[data-slot="import-file"]').click(); });
  marinara.on(editor, "submit", (event) => { event.preventDefault(); void saveProject(); }); marinara.on(editor, "input", (event) => { if (event.target === fields.analysisRules) { $('[data-slot="rules-count"]').textContent = String(event.target.value.length); $('[data-slot="rules-state"]').textContent = "Alterações não salvas"; return; } state.dirty = true; $('[data-slot="save-state"]').textContent = "Unsaved changes"; $('[data-slot="source-count"]').textContent = String(fields.sourceText.value.length); errors([]); }); marinara.on($('[data-slot="import-file"]'), "change", (event) => { void importJson(event.target.files?.[0]); event.target.value = ""; }); marinara.on(document, "keydown", (event) => { if (!state.open) return; if (event.key === "Escape") closePanel(); if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "s") { event.preventDefault(); void saveProject(); } });
  marinara.onCleanup(() => { document.body.classList.remove("nd-body-locked"); api.clearLastRawResponse(); delete globalThis.__narrativeDirectorLoaded; delete globalThis.__NarrativeDirectorCore; delete globalThis.__NarrativeDirectorStorage; delete globalThis.__NarrativeDirectorApi; });
})();
