import assert from "node:assert/strict";
await import("../src/core.js");
const core = globalThis.__NarrativeDirectorCore;
const story = { title: "Fictional smoke", mainCharacterId: "traveler", worldCard: { name: "Station", description: "A traveler reaches a public station.", personality: "Quiet", scenario: "Arrival" }, characters: [{ id: "traveler", name: "Traveler", aliases: [], isMain: true, public: { role: "Traveler", description: "A known traveler.", appearance: "Green coat.", personality: "Patient.", scenario: "At the station." }, curatorNotes: "Carries a hidden map." }], relationships: [], worldEntries: [{ id: "station", name: "Station", keys: ["station"], content: "Trains leave hourly." }], curatorGuide: "The hidden route remains private.", secrets: [{ id: "route", title: "Hidden route", truth: "The route reaches a refuge.", knownByCharacterIds: ["traveler"], revealCondition: "The map is shown.", status: "locked" }], storylines: [{ id: "journey", title: "Journey", direction: "The journey may deepen.", status: "active" }] };
const project = core.createProject({ id: "smoke", story });
assert.equal(project.schemaVersion, 4);
assert.deepEqual(Object.keys(core.buildLorebookTransport(project)), ["curator"]);
assert.match(JSON.stringify(core.buildCuratorDocument(project)), /hidden route/i);
assert.equal(core.importBundle(core.exportBundle([project])).length, 1);
process.stdout.write("Narrative Curator v4 isolated smoke passed.\n");
